package com.hanghai.kchtg.gis.search.dto;

public enum KchtType {
    CANGBIEN,
    BENCANG,
    CAUCANG,
    CANGCAN,
    VUNGNUOC,
    DIKE_REVETMENT,
    NAVIGATION_CHANNEL,
    COSO_SUACHUA,
    DENBIEN,
    PHAOTIEU,
    HE_THONG_VTS,
    TRAM_RADAR,
    BENPHAO,
    KHUNEO_DAU,
    KHUCHUYEN_TAI,
    KHUTRANH_TRU_BAO,
    DAI_TTDH,
    DAI_INMARSAT,
    DAI_COSPAS_SARSAT,
    DAI_LRIT,
    DAI_HANOI,
    NHATRAM_PHAO
}
