services:
  vmd-csdl-v2:
    image: registry.etc.vn/hang-hai-kchtgt-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET:-Chuyen-Doi-So-2026-QuanTriHeThong-JWT-Secret-Key-256bit}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-Q3V0-Loc-2026-AES-256-Encryption-Key-B64}
      - REDIS_HOST=redis
      - DB_HOST=${DB_HOST:-10.0.229.20}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-vmd_csdl_v2}
      - DB_USER=${DB_USER:-vmd_mtis_geo}
      - DB_PASS=${DB_PASS:-VmdMtisPostgis@123}
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: registry.etc.vn/library/redis:8.0.2-alpine
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    image: registry.etc.vn/hang-hai-kchtgt-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:80"
    restart: always
    depends_on:
      vmd-csdl-v2:
        condition: service_healthy
