
services:
  backend:
    image: registry.etc.vn/hang-hai-kchtgt-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - REDIS_HOST=redis
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: registry.etc.vn/library/redis:8.0.2-alpine
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    image: registry.etc.vn/hang-hai-kchtgt-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:80"
    restart: always
    depends_on:
      backend:
        condition: service_healthy
