package com.hanghai.kchtg.datasharingaggregation.enums;

public enum SharingType {
    DE_CHAN_SONG_DE_CHAN_CAT,
    LUONG_HANG_HAI,
    DAI_TTDH,
    DAI_INMARSAT,
    DAI_COSPAS_SARSAT,
    DAI_LRIT,
    DAI_HANG_HAI_HN,
    CANG_CAN,
    TRANG_THAI_HOAT_DONG_KCHTGT,
    THONG_TIN_TAI_SAN_KCHTGT,
    THONG_TIN_TONG_HOP_KCHTGT,
    THONG_TIN_BAO_TRI_KCHTGT,
    TONG_HOP_KCHTGT_CANG_BIEN,
    TONG_HOP_KCHTGT_BEN_CANG_CAU_CANG,
    TONG_HOP_KCHTGT_LUONG_HANG_HAI,
    TONG_HOP_KCHTGT_KHU_CHUYEN_TAI_NEU_DAU,
    TONG_HOP_KCHTGT_PHAO_TIEU,
    TONG_HOP_KCHTGT_HE_THONG_DEN_BIEN,
    TONG_HOP_KCHTGT_HE_THONG_DE_KE
}
