server:
  port: 8081
  max-http-header-size: 32KB
  max-http-request-header-size: 32KB
  tomcat:
    max-http-header-size: 32KB

spring:
  flyway:
    enabled: true
    out-of-order: true
    validate-on-migrate: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:10.0.229.20}:${DB_PORT:5432}/${DB_NAME:vmd_csdl_v2_dev}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:admin}
    password: ${DB_PASS:Etc@1234}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hbm2ddl.auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
logging:
  level:
    root: WARN
    org.hibernate: ERROR
    org.springframework.security: WARN
    com.hanghai.kchtg: INFO

app:
  frontend-url: ${APP_FRONTEND_URL:http://10.0.229.20:30008}

