spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kchtg_m001}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:kchtg}
    password: ${DB_PASS:kchtg}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
logging:
  level:
    root: WARN
    org.hibernate: ERROR
    org.springframework.security: WARN
    com.hanghai.kchtg: INFO
