spring:
  datasource:
    url: jdbc:postgresql://10.0.229.20:5432/vmd_csdl_v2
    driver-class-name: org.postgresql.Driver
    username: vmd_mtis_geo
    password: VmdMtisPostgis@123
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
logging:
  level:
    root: WARN
    org.hibernate: ERROR
    org.springframework.security: WARN
    com.hanghai.kchtg: INFO
