-- ============================================================
-- Seed Reference Data for ObjectCategories, LineCategories,
-- PolygonCategories, and MapIcons
-- ============================================================
-- Generated: 2026-06-19
-- Schema notes:
--   - id             → UUID() generated by H2
--   - created_at     → CURRENT_TIMESTAMP()
--   - updated_at     → CURRENT_TIMESTAMP()
--   - MapIcon.category → enum: BUOY, LIGHTHOUSE, BEACON, WHARF, OTHER
-- ============================================================

-- 1. ObjectCategories (POINT objects) — 5 records
INSERT INTO object_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_PORT', 'Cảng biển', 'Cảng biển chính và phụ', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO object_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_LIGHTHOUSE', 'Đèn biển', 'Đèn biển, hải đăng', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO object_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_BUOY', 'Phao tiêu', 'Phao tiêu hàng hải', 3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO object_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_BEACON', 'Đèn hiệu', 'Đèn hiệu hàng hải', 4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO object_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_OTHER', 'Khác', 'Đối tượng khác thuộc loại Point', 5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- 2. LineCategories (LINE objects) — 4 records
INSERT INTO line_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_COASTLINE', 'Đường bờ biển', 'Đường bờ biển tự nhiên hoặc nhân tạo', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO line_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_SHIPPING_ROUTE', 'Tuyến hàng hải', 'Tuyến đường hàng hải được quy hoạch', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO line_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_WATERWAY', 'Đường thủy', 'Đường thủy nội địa hoặc ven biển', 3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO line_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_OTHER', 'Khác', 'Đường line khác', 4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- 3. PolygonCategories (POLYGON objects) — 6 records
INSERT INTO polygon_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_WATER_ZONE', 'Vùng nước', 'Khu vực vùng nước', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO polygon_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_ANCHORAGE', 'Vùng neo đậu', 'Khu vực neo đậu tàu thuyền', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO polygon_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_STORM_SHELTER', 'Nơi tránh bão', 'Nơi trú ẩn, tránh bão', 3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO polygon_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_RESTRICTED', 'Khu vực cấm', 'Khu vực cấm vào / cấm hoạt động', 4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO polygon_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_LIMITED', 'Khu vực hạn chế', 'Khu vực hạn chế hoạt động', 5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO polygon_categories (id, code, name, description, sort_order, created_at, updated_at) VALUES (UUID(), 'CAT_OTHER', 'Khác', 'Polygon khác', 6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- 4. MapIcons — 15 records
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_PORT', 'Cảng biển', 'WHARF', '/icons/port.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_LIGHTHOUSE', 'Đèn biển', 'LIGHTHOUSE', '/icons/lighthouse.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_BUOY', 'Phao tiêu', 'BUOY', '/icons/buoy.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_BEACON', 'Đèn hiệu', 'BEACON', '/icons/beacon.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_DEFAULT', 'Khác', 'OTHER', '/icons/default.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_COASTLINE', 'Đường bờ biển', 'OTHER', '/icons/coastline.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_SHIPPING_ROUTE', 'Tuyến hàng hải', 'OTHER', '/icons/shipping_route.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_WATERWAY', 'Đường thủy', 'OTHER', '/icons/waterway.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_DEFAULT_LINE', 'Khác (LINE)', 'OTHER', '/icons/line_default.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_WATER_ZONE', 'Vùng nước', 'OTHER', '/icons/water_zone.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_ANCHORAGE', 'Vùng neo đậu', 'OTHER', '/icons/anchorage.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_STORM_SHELTER', 'Nơi tránh bão', 'OTHER', '/icons/storm_shelter.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_RESTRICTED', 'Khu vực cấm', 'OTHER', '/icons/restricted.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_LIMITED', 'Khu vực hạn chế', 'OTHER', '/icons/limited.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO map_icons (id, code, name, category, icon_url, size, status, created_at, updated_at) VALUES (UUID(), 'ICON_DEFAULT_POLY', 'Khác (POLYGON)', 'OTHER', '/icons/poly_default.png', NULL, 'ACTIVE', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
