package com.hanghai.kchtg.navigationchannel;

import com.hanghai.kchtg.common.entity.InfrastructureHistory;
import com.hanghai.kchtg.common.entity.ApprovalStatus;
import com.hanghai.kchtg.common.repository.InfrastructureHistoryRepository;
import com.hanghai.kchtg.common.repository.InfrastructureAttachmentRepository;
import com.hanghai.kchtg.common.service.InfrastructureApprovalService;
import com.hanghai.kchtg.gis.spatial.service.GisSpatialObjectService;
import com.hanghai.kchtg.navigationchannel.controller.NavigationChannelController;
import com.hanghai.kchtg.navigationchannel.dto.ChannelRouteDetailRequest;
import com.hanghai.kchtg.navigationchannel.entity.ChannelRouteDetail;
import com.hanghai.kchtg.navigationchannel.entity.NavigationChannel;
import com.hanghai.kchtg.navigationchannel.repository.NavigationChannelRepository;
import com.hanghai.kchtg.navigationchannel.service.NavigationChannelService;
import com.hanghai.kchtg.orgunit.repository.OrgUnitRepository;
import com.hanghai.kchtg.orgunit.service.OrgUnitCacheService;
import com.hanghai.kchtg.orgunit.service.OrgUnitScopeService;
import com.hanghai.kchtg.user.repository.UserRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.lang.reflect.Method;
import java.util.Collections;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.isNull;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Regression tests for the F-038 rework round (QA/reviewer Changes-requested).
 * <ul>
 *   <li>F1 — {@code approvalStatus} camelCase query param binds through controller → service → repository
 *       (AC-038-01 StatusTabs filter/counts).</li>
 *   <li>BR-038-03 — {@code routeCode} (#23) server-side generated by {@code toRouteDetail}
 *       as {@code {channelCode}-{NN}}; never NULL (F151 maTuyenLuong).</li>
 * </ul>
 * Pure Mockito unit tests — no Spring context (the pre-existing Flyway failure at
 * V20260822130000:49 blocks any context bootstrap; out of F-038 scope).
 */
@ExtendWith(MockitoExtension.class)
class NavigationChannelServiceTest {

    @Mock
    private NavigationChannelRepository repo;
    @Mock
    private InfrastructureHistoryRepository approvalHistoryRepo;
    @Mock
    private InfrastructureApprovalService approvalService;
    @Mock
    private GisSpatialObjectService gisSpatialObjectService;
    @Mock
    private OrgUnitRepository orgUnitRepository;
    @Mock
    private OrgUnitCacheService orgUnitCacheService;
    @Mock
    private OrgUnitScopeService orgUnitScopeService;
    @Mock
    private InfrastructureAttachmentRepository attachmentRepository;
    @Mock
    private UserRepository userRepository;

    @InjectMocks
    private NavigationChannelService service;

    /** Pure mock for the controller-binding tests (F1) — the @InjectMocks instance is a REAL service. */
    @Mock
    private NavigationChannelService controllerService;

    // ── F1: approvalStatus (camelCase) binding ─────────────────────────────

    @Test
    @DisplayName("F1: /search?approvalStatus=PROPOSED binds the camelCase param and forwards it to the service")
    void search_bindsCamelCaseApprovalStatusParam() throws Exception {
        MockMvc mockMvc = MockMvcBuilders.standaloneSetup(new NavigationChannelController(controllerService)).build();

        mockMvc.perform(get("/api/v1/navigation-channel/search").param("approvalStatus", "PROPOSED"))
                .andExpect(status().isOk());

        verify(controllerService).searchDocuments(
                isNull(), isNull(), isNull(), isNull(), isNull(), eq("PROPOSED"), eq(0), eq(20));
    }

    @Test
    @DisplayName("F1: legacy /search?ApprovalStatus=... (wrong case) must NOT bind — status stays null")
    void search_doesNotBindPascalCaseApprovalStatusParam() throws Exception {
        MockMvc mockMvc = MockMvcBuilders.standaloneSetup(new NavigationChannelController(controllerService)).build();

        mockMvc.perform(get("/api/v1/navigation-channel/search").param("ApprovalStatus", "PROPOSED"))
                .andExpect(status().isOk());

        verify(controllerService).searchDocuments(
                isNull(), isNull(), isNull(), isNull(), isNull(), isNull(), eq(0), eq(20));
    }

    @Test
    @DisplayName("F1: service parses status string to enum and forwards it to the repository")
    void searchDocuments_forwardsParsedApprovalStatus() {
        Page<NavigationChannel> empty = new PageImpl<>(Collections.emptyList());
        when(repo.searchDocuments(any(), any(), any(), any(), any(), any(), any())).thenReturn(empty);

        service.searchDocuments(null, null, null, null, null, "  PROPOSED  ", 0, 20);

        verify(repo).searchDocuments(
                isNull(), isNull(), isNull(), isNull(), isNull(), eq(ApprovalStatus.PROPOSED), any());
    }

    @Test
    @DisplayName("F1: invalid status string is ignored — repository called with null status")
    void searchDocuments_ignoresInvalidStatus() {
        Page<NavigationChannel> empty = new PageImpl<>(Collections.emptyList());
        when(repo.searchDocuments(any(), any(), any(), any(), any(), any(), any())).thenReturn(empty);

        service.searchDocuments(null, null, null, null, null, "NOT_A_STATUS", 0, 20);

        verify(repo).searchDocuments(
                isNull(), isNull(), isNull(), isNull(), isNull(), isNull(), any());
    }

    // ── BR-038-03: routeCode server-side generation ────────────────────────

    @Test
    @DisplayName("BR-038-03: toRouteDetail generates routeCode {channelCode}-{sequenceNo}")
    void toRouteDetail_generatesRouteCodeFromSequenceNo() throws Exception {
        NavigationChannel nc = NavigationChannel.builder().channelCode("LHH000001").build();
        ChannelRouteDetailRequest d = ChannelRouteDetailRequest.builder().sequenceNo(3).build();

        ChannelRouteDetail detail = invokeToRouteDetail(d, nc, 0);

        assertThat(detail.getRouteCode()).isEqualTo("LHH000001-03");
        assertThat(detail.getSequenceNo()).isEqualTo(3);
    }

    @Test
    @DisplayName("BR-038-03: toRouteDetail falls back to list index+1 when sequenceNo is null — routeCode never NULL")
    void toRouteDetail_routeCodeFallsBackToListIndex() throws Exception {
        NavigationChannel nc = NavigationChannel.builder().channelCode("LHH000042").build();
        ChannelRouteDetailRequest d = ChannelRouteDetailRequest.builder().build(); // sequenceNo null

        ChannelRouteDetail detail = invokeToRouteDetail(d, nc, 2); // row 3 → index 2 → 03

        assertThat(detail.getRouteCode()).isEqualTo("LHH000042-03");
        assertThat(detail.getSequenceNo()).isEqualTo(3);
    }

    private ChannelRouteDetail invokeToRouteDetail(ChannelRouteDetailRequest d, NavigationChannel nc, int index)
            throws Exception {
        Method method = NavigationChannelService.class.getDeclaredMethod(
                "toRouteDetail", ChannelRouteDetailRequest.class, NavigationChannel.class, int.class);
        method.setAccessible(true);
        return (ChannelRouteDetail) method.invoke(service, d, nc, index);
    }
}
