package com.hanghai.kchtg.businessintegration.enums;

public enum IntegrationType {
    TAU_BIEN_RA_VAO_CANG,
    PHUONG_TIEN_THUY_NOI_DIA,
    TAU_BIEN_NUOC_NGOAI,
    TAU_BIEN_VN_QUOC_TE,
    KHOI_LUONG_HANG_HOA_HANH_KHACH,
    LUOT_TAU_THUYEN_VAO_ROI_CANG,
    KHOI_LUONG_HANG_HOA_DOI_TAU_VN,
    KHOI_LUONG_HANG_HOA_KHU_QUAN_LY,
    THUYEN_VIEN_HOA_TIEU,
    TAU_BIEN_CO_QUOC_TICH_VN,
    TAU_THUYEN_LAI_DAT,
    CO_SO_DONG_MOI_SUA_CHUA,
    NANG_LUC_THONG_QUA_BEN_CANG,
    NANG_LUC_THONG_QUA_CANG,
    KHOI_LUONG_HANG_HOA_THEO_THANG,
    KHOI_LUONG_HANG_HOA_THEO_NAM,
    SAN_LUONG_DICH_VU_VAN_TAI
}
