ALTER TABLE vts_system ADD COLUMN IF NOT EXISTS code VARCHAR(50) UNIQUE;
ALTER TABLE vts_system ADD COLUMN IF NOT EXISTS province VARCHAR(255);
ALTER TABLE vts_system ADD COLUMN IF NOT EXISTS address VARCHAR(500);
ALTER TABLE vts_system ADD COLUMN IF NOT EXISTS maritime_notice VARCHAR(2000);
ALTER TABLE vts_system ADD COLUMN IF NOT EXISTS operation_start_date DATE;
