ALTER TABLE app_roles ADD COLUMN IF NOT EXISTS name VARCHAR(100);
ALTER TABLE app_roles ADD COLUMN IF NOT EXISTS description VARCHAR(500);
ALTER TABLE app_roles ADD COLUMN IF NOT EXISTS level INTEGER NOT NULL DEFAULT 99;
ALTER TABLE app_roles ADD COLUMN IF NOT EXISTS is_system BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE app_roles ADD COLUMN IF NOT EXISTS hierarchy_depth INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_roles ADD COLUMN IF NOT EXISTS user_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_roles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE app_roles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE app_roles ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE app_roles ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'ACTIVE';

ALTER TABLE app_roles DROP CONSTRAINT IF EXISTS app_roles_status_check;
ALTER TABLE app_roles ALTER COLUMN status DROP DEFAULT;

ALTER TABLE app_roles 
ALTER COLUMN status TYPE integer 
USING CASE 
    WHEN status::text = '0' THEN 0
    WHEN status::text = '1' THEN 1
    WHEN status::text = '2' THEN 2
    WHEN status = 'ACTIVE' THEN 0 
    WHEN status = 'INACTIVE' THEN 1 
    WHEN status = 'DELETED' THEN 2 
    ELSE 0 
END;

ALTER TABLE app_roles ALTER COLUMN status SET DEFAULT 0;


