ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS parent_org_unit_id UUID;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS org_unit_id UUID;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS using_org_unit_id UUID;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS berth_id UUID;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS barcode VARCHAR(100);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS asset_condition VARCHAR(100);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS usage_status VARCHAR(100);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS asset_group VARCHAR(200);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS asset_subgroup VARCHAR(200);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS address VARCHAR(500);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS origin VARCHAR(200);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS quantity NUMERIC(15,3);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS quantity_unit VARCHAR(50);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS model VARCHAR(100);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS serial_number VARCHAR(100);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS country_of_origin VARCHAR(100);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS manufacturer VARCHAR(200);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS construction_year INTEGER;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS use_date DATE;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS land_area NUMERIC(15,3);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS floor_area NUMERIC(15,3);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS asset_location VARCHAR(500);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS attachment_name VARCHAR(500);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS declaration_date DATE;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS depreciation_rate NUMERIC(7,4);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS assignment_decision_number VARCHAR(200);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS depreciation_start_date DATE;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS depreciation_months INTEGER;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS depreciation_end_date DATE;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS monthly_depreciation NUMERIC(15,2);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS disposal_method VARCHAR(200);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS approval_status INTEGER DEFAULT 0;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS submitted_by UUID;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS port_authority_approved_by UUID;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS port_authority_approved_at TIMESTAMPTZ;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS port_authority_approval_content VARCHAR(1000);
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS department_approved_by UUID;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS department_approved_at TIMESTAMPTZ;
ALTER TABLE infra_assets ADD COLUMN IF NOT EXISTS department_approval_content VARCHAR(1000);

CREATE INDEX IF NOT EXISTS idx_infra_assets_berth_id ON infra_assets(berth_id);
CREATE INDEX IF NOT EXISTS idx_infra_assets_org_unit_id ON infra_assets(org_unit_id);
CREATE INDEX IF NOT EXISTS idx_infra_assets_using_org_unit_id ON infra_assets(using_org_unit_id);
CREATE INDEX IF NOT EXISTS idx_infra_assets_type_status ON infra_assets(asset_type, approval_status);

ALTER TABLE asset_exploitations ADD COLUMN IF NOT EXISTS operator_org_unit_id UUID;
ALTER TABLE asset_exploitations ADD COLUMN IF NOT EXISTS asset_category VARCHAR(200);
ALTER TABLE asset_exploitations ADD COLUMN IF NOT EXISTS unit_of_measure VARCHAR(50);
ALTER TABLE asset_exploitations ADD COLUMN IF NOT EXISTS quantity NUMERIC(15,3);
ALTER TABLE asset_exploitations ADD COLUMN IF NOT EXISTS exploitation_deadline DATE;
ALTER TABLE asset_exploitations ADD COLUMN IF NOT EXISTS total_revenue NUMERIC(15,2);
ALTER TABLE asset_exploitations ADD COLUMN IF NOT EXISTS related_costs NUMERIC(15,2);
ALTER TABLE asset_exploitations ADD COLUMN IF NOT EXISTS state_budget_payment NUMERIC(15,2);
ALTER TABLE asset_exploitations ADD COLUMN IF NOT EXISTS project_amount NUMERIC(15,2);

ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS decision_number VARCHAR(200);
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS decision_date DATE;
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS adjustment_date DATE;
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS adjustment_reason VARCHAR(200);
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS adjustment_notes VARCHAR(1000);
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS original_value_before NUMERIC(15,2);
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS original_value_after NUMERIC(15,2);
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS remaining_value_before NUMERIC(15,2);
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS remaining_value_after NUMERIC(15,2);
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS declaration_date DATE;
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS depreciation_rate NUMERIC(7,4);
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS value_unit VARCHAR(10);
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS assignment_decision_number VARCHAR(200);
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS depreciation_start_date DATE;
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS depreciation_months INTEGER;
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS depreciation_end_date DATE;
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS adjustment_accumulated_depreciation NUMERIC(15,2);
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS monthly_depreciation NUMERIC(15,2);
ALTER TABLE asset_increase_requests ADD COLUMN IF NOT EXISTS disposal_method VARCHAR(200);

ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS decision_number VARCHAR(200);
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS decision_date DATE;
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS adjustment_date DATE;
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS adjustment_reason VARCHAR(200);
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS adjustment_notes VARCHAR(1000);
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS original_value_before NUMERIC(15,2);
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS original_value_after NUMERIC(15,2);
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS remaining_value_before NUMERIC(15,2);
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS remaining_value_after NUMERIC(15,2);
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS declaration_date DATE;
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS depreciation_rate NUMERIC(7,4);
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS value_unit VARCHAR(10);
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS assignment_decision_number VARCHAR(200);
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS depreciation_start_date DATE;
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS depreciation_months INTEGER;
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS depreciation_end_date DATE;
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS adjustment_accumulated_depreciation NUMERIC(15,2);
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS monthly_depreciation NUMERIC(15,2);
ALTER TABLE asset_decrease_requests ADD COLUMN IF NOT EXISTS disposal_method VARCHAR(200);
