-- Migration: Create dedicated tables for Task [59] Tai san HT truyen dan
-- Tables: transmission_assets, transmission_asset_exploitations, transmission_asset_adjustments

CREATE TABLE IF NOT EXISTS transmission_assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_code VARCHAR(50) UNIQUE NOT NULL,
    asset_name VARCHAR(200) NOT NULL,
    parent_org_unit_id UUID,
    org_unit_id UUID,
    using_org_unit_id UUID,
    transmission_id UUID,
    asset_type VARCHAR(100) DEFAULT 'Tài sản HT truyền dẫn',
    barcode VARCHAR(100),
    asset_condition VARCHAR(100) DEFAULT 'Tốt',
    usage_status VARCHAR(100) DEFAULT 'Đang sử dụng',
    asset_group VARCHAR(200),
    asset_subgroup VARCHAR(200),
    address VARCHAR(500),
    origin VARCHAR(200),
    quantity NUMERIC(15,3) DEFAULT 1,
    quantity_unit VARCHAR(50) DEFAULT 'Bộ',
    model VARCHAR(100),
    serial_number VARCHAR(100),
    country_of_origin VARCHAR(100),
    manufacturer VARCHAR(200),
    construction_year INTEGER,
    use_date DATE,
    land_area NUMERIC(15,3),
    floor_area NUMERIC(15,3),
    asset_location VARCHAR(500),
    attachment_name VARCHAR(500),
    declaration_date DATE,
    original_value NUMERIC(15,2) DEFAULT 0,
    depreciation_rate NUMERIC(7,4) DEFAULT 0,
    accumulated_depreciation NUMERIC(15,2) DEFAULT 0,
    remaining_value NUMERIC(15,2) DEFAULT 0,
    assignment_decision_number VARCHAR(200),
    depreciation_start_date DATE,
    depreciation_months INTEGER DEFAULT 0,
    depreciation_end_date DATE,
    monthly_depreciation NUMERIC(15,2) DEFAULT 0,
    disposal_method VARCHAR(200),
    status VARCHAR(50) DEFAULT 'MANAGED',
    approval_status INTEGER DEFAULT 0,
    submitted_by UUID,
    submitted_at TIMESTAMPTZ,
    port_authority_approved_by UUID,
    port_authority_approved_at TIMESTAMPTZ,
    port_authority_approval_content VARCHAR(1000),
    department_approved_by UUID,
    department_approved_at TIMESTAMPTZ,
    department_approval_content VARCHAR(1000),
    rejection_reason VARCHAR(1000),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,
    lock_version INTEGER DEFAULT 0,
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_transmission_assets_org ON transmission_assets(org_unit_id);
CREATE INDEX IF NOT EXISTS idx_transmission_assets_using_org ON transmission_assets(using_org_unit_id);
CREATE INDEX IF NOT EXISTS idx_transmission_assets_transmission_id ON transmission_assets(transmission_id);
CREATE INDEX IF NOT EXISTS idx_transmission_assets_approval_status ON transmission_assets(approval_status);

CREATE TABLE IF NOT EXISTS transmission_asset_exploitations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID NOT NULL REFERENCES transmission_assets(id) ON DELETE CASCADE,
    operator_org_unit_id UUID,
    asset_category VARCHAR(200),
    unit_of_measure VARCHAR(50) DEFAULT 'Bộ',
    quantity NUMERIC(15,3) DEFAULT 1,
    exploitation_deadline DATE,
    total_revenue NUMERIC(15,2) DEFAULT 0,
    related_costs NUMERIC(15,2) DEFAULT 0,
    state_budget_payment NUMERIC(15,2) DEFAULT 0,
    project_amount NUMERIC(15,2) DEFAULT 0,
    operating_time VARCHAR(200),
    exploitation_level VARCHAR(100),
    operating_cost NUMERIC(15,2) DEFAULT 0,
    maintenance_cost NUMERIC(15,2) DEFAULT 0,
    technical_status VARCHAR(100),
    exploitation_month INTEGER,
    exploitation_year INTEGER,
    description VARCHAR(1000),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID
);

CREATE INDEX IF NOT EXISTS idx_transmission_exploitations_asset_id ON transmission_asset_exploitations(asset_id);

CREATE TABLE IF NOT EXISTS transmission_asset_adjustments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID NOT NULL REFERENCES transmission_assets(id) ON DELETE CASCADE,
    adjustment_type VARCHAR(50) NOT NULL,
    decision_number VARCHAR(200),
    decision_date DATE,
    adjustment_date DATE,
    adjustment_reason VARCHAR(200),
    notes VARCHAR(1000),
    original_value_before NUMERIC(15,2) DEFAULT 0,
    original_value_after NUMERIC(15,2) DEFAULT 0,
    remaining_value_before NUMERIC(15,2) DEFAULT 0,
    remaining_value_after NUMERIC(15,2) DEFAULT 0,
    declaration_date DATE,
    depreciation_rate NUMERIC(7,4) DEFAULT 0,
    assignment_decision_number VARCHAR(200),
    depreciation_start_date DATE,
    depreciation_months INTEGER DEFAULT 0,
    depreciation_end_date DATE,
    accumulated_depreciation NUMERIC(15,2) DEFAULT 0,
    monthly_depreciation NUMERIC(15,2) DEFAULT 0,
    disposal_method VARCHAR(200),
    submitted_by UUID,
    submitted_at TIMESTAMPTZ,
    port_authority_approved_by UUID,
    port_authority_approved_at TIMESTAMPTZ,
    port_authority_approval_content VARCHAR(1000),
    department_approved_by UUID,
    department_approved_at TIMESTAMPTZ,
    department_approval_content VARCHAR(1000),
    status VARCHAR(50) DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID
);

CREATE INDEX IF NOT EXISTS idx_transmission_adjustments_asset_id ON transmission_asset_adjustments(asset_id);
