CREATE TABLE ts_ql (
    id UUID PRIMARY KEY,
    org_unit_id UUID,
    nhom VARCHAR(20) NOT NULL,
    ts_ma VARCHAR(50),
    ts_ten VARCHAR(500) NOT NULL,
    don_vi_tinh VARCHAR(100),
    so_luong NUMERIC(10,2),
    nam_xay_dung INT,
    nam_su_dung INT,
    dien_tich_dat NUMERIC(15,2),
    san_su_dung NUMERIC(15,2),
    nguyen_gia NUMERIC(20,4),
    gia_tri_con_lai NUMERIC(20,4),
    hao_mon_luy_ke NUMERIC(20,4),
    tinh_trang VARCHAR(200),
    ghi_chu VARCHAR(500),
    ngay_ke_khai DATE,
    hinh_thuc_xu_ly VARCHAR(100),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE bcc157_report (
    id UUID PRIMARY KEY,
    org_unit_id UUID NOT NULL,
    report_year INT NOT NULL,
    nguon_du_lieu VARCHAR(10),
    status VARCHAR(20),
    ma_so_nguyen_gia_so_du_dau_nam VARCHAR(20),
    tai_san_nguyen_gia_so_du_dau_nam NUMERIC(20,4),
    ma_so_nguyen_gia_tang_trong_nam VARCHAR(20),
    tai_san_nguyen_gia_tang_trong_nam NUMERIC(20,4),
    ma_so_nguyen_gia_giam_trong_nam VARCHAR(20),
    tai_san_nguyen_gia_giam_trong_nam NUMERIC(20,4),
    ma_so_nguyen_gia_so_du_cuoi_nam VARCHAR(20),
    tai_san_nguyen_gia_so_du_cuoi_nam NUMERIC(20,4),
    ma_so_gia_tri_hao_mon_so_du_dau_nam VARCHAR(20),
    tai_san_gia_tri_hao_mon_so_du_dau_nam NUMERIC(20,4),
    ma_so_gia_tri_hao_mon_tang_trong_nam VARCHAR(20),
    tai_san_gia_tri_hao_mon_tang_trong_nam NUMERIC(20,4),
    ma_so_gia_tri_hao_mon_giam_trong_nam VARCHAR(20),
    tai_san_gia_tri_hao_mon_giam_trong_nam NUMERIC(20,4),
    ma_so_gia_tri_hao_mon_so_du_cuoi_nam VARCHAR(20),
    tai_san_gia_tri_hao_mon_so_du_cuoi_nam NUMERIC(20,4),
    ma_so_gia_tri_con_lai_tu_ngay_dau_nam VARCHAR(20),
    tai_san_gia_tri_con_lai_tu_ngay_dau_nam NUMERIC(20,4),
    ma_so_gia_tri_con_lai_tu_ngay_cuoi_nam VARCHAR(20),
    tai_san_gia_tri_con_lai_tu_ngay_cuoi_nam NUMERIC(20,4),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uq_bcc157_report UNIQUE (org_unit_id, report_year, nguon_du_lieu)
);
